version: '3.8'

services:
  flask-app:
    build: .
    container_name: k8proj
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FLASK_ENV=development
    volumes:
      - .:/app
