apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8proj
spec:
    replicas: 2
    selector:
        matchLabels:
            app: k8proj
    template:
        metadata:
            labels:
                app: k8proj
        spec:
            containers:
                - name: k8proj-main
                  image: docker.io/djay1720/my-image:latest
                  ports:
                   - containerPort: 8000
